---
- name: Change root password
  hosts: "{{ target_hosts | default('linux') }}"
  become: true
  vars:
    root_password: "{{ new_root_password }}"
    root_password_salt: a;slkdfa;slna

  tasks: 
    - name: Change root password
      ansible.builtin.user: 
        name: root
        password: "{{ root_password | password_hash(salt=root_password_salt) }}
        
# When running this playbook type: 
# ansible run change_root_password.yml -e new_root_password=lovemywife
