---
- name: Configure NTP on hosts
  hosts: CRIA
  become: true
  tasks:
    - name: Ensure chrony is installed
      dnf:
        name: chrony
        state: present

    - name: Move file over
      copy:
        src: /home/mitchell/ansible_training/chrony.conf
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      service:
        name: chronyd
        state: restarted
        enabled: yes